// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        ext.kotlin_version = '2.1.0'
    }
    repositories {
        jcenter()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

task checkRepoName {
    doFirst {
        def repo = System.getenv('JITPACK_REPO') ?: System.getenv('REPOSITORY')
        def branch = System.getenv('JITPACK_BRANCH') ?: System.getenv('BRANCH')

        if (repo != null && repo != 'Kount/kount-android-sdk') {
            throw new GradleException("Este proyecto solo puede ser compilado desde el repositorio 'Kount/kount-android-sdk'. Repositorio detectado: " + repo)
        }
        else if (branch != null && branch != 'master') {
            throw new GradleException("Este proyecto solo puede ser compilado desde la rama 'master'. Rama detectada: " + branch)
        }
        else {
            println "Building from the correct repository: " + (repo ?: "local build") + " and branch: " + (branch ?: "local branch")
        }
    }
}
